[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]
command = "Hyprland --config /etc/greetd/hyprland-greeter.conf"
user = "greeter"


[initial_session]
command = "uwsm start hyprland.desktop"
user = "israel"
