[background]
path = "/usr/share/wallpapers/Astronaut4.png"
fit = "Cover"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[appearance]
gtk_theme = "Adwaita-dark"
icon_theme = "Papirus-Dark"
cursor_theme = "Bibata-Modern-Ice"
font = "Inter 11"

[GTK]
application_prefer_dark_theme = true
